[[buildpacks]]
id = "paketo-buildpacks/java-native-image"
version = "3.0.0"
image = "gcr.io/paketo-buildpacks/java-native-image:3.0.0"

[[order]]
group = [
    { id = "paketo-buildpacks/java-native-image", version = "3.0.0" }
]

[stack]
id = "io.buildpacks.stacks.bionic"
run-image = "gcr.io/paketo-buildpacks/run:base-cnb"
build-image = "gcr.io/paketo-buildpacks/build:base-cnb"